allocator/urls.py
from django.urls import path
from .views import (
    IndexView,
    logout_view,
    DashboardView,
    TaskView,
    DeleteTaskView,
    CompleteSubTaskView,
    NotificationView,
    AllNotificationsView,
    DeleteNotificationView,
    EmployeeTasksView,
    AllProjectsView,
    ProjectView,
    DeleteProjectView,
    AllUserView,
    EditProjectView,
    DeactivateUserView
)

app_name = 'allocator'

urlpatterns = [
    path('', IndexView.as_view(), name='landing'),
    path('logout/', logout_view, name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('tasks/', EmployeeTasksView.as_view(), name='employee_tasks'),
    path('tasks/<int:id>/', TaskView.as_view(), name='task'),
    path('tasks/<int:id>/delete', DeleteTaskView.as_view(), name='delete_task'),
    path('tasks/<int:taskid>/<int:subid>', CompleteSubTaskView.as_view(), name='complete_task'),
    path('notifications/', AllNotificationsView.as_view(), name='all_notifications'),
    path('notifications/<int:id>/', NotificationView.as_view(), name='notification'),
    path('notifications/<int:id>/delete', DeleteNotificationView.as_view(), name='delete_notification'),
    path('projects/', AllProjectsView.as_view(), name='all_projects'),
    path('projects/<int:id>/', ProjectView.as_view(), name='project'),
    path('projects/<int:id>/delete', DeleteProjectView.as_view(), name='delete_project'),
    path('projects/<int:id>/edit', EditProjectView.as_view(), name='edit_project'),
    path('users/', AllUserView.as_view(), name='users'),
    path('users/<int:id>/deactivate', DeactivateUserView.as_view(), name='deactivate_user'),
]

taskallocator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('allocator.urls'))
]

allocator/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User


# Create your models here.


class User(AbstractUser):
    is_manager = models.BooleanField(default=False)
    is_employee = models.BooleanField(default=False)

    def __str__(self):
        return self.first_name
    
    @property
    def pending_tasks(self):
        tasks = Task.objects.filter(user_id=self.pk)
        return tasks.count()


class Project(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=40)
    start = models.DateField(auto_now_add=True)
    end = models.DateField()

    def __str__(self):
        return self.name

    @property
    def progress(self):
        tasks = Task.objects.filter(project_id=self.pk)
        all_subs = 0
        completed = 0
        for t in tasks:
            subtasks = SubTask.objects.filter(task_id=t.id)
            all_subs += subtasks.count()
            for sub in subtasks:
                if sub.is_completed:
                    completed += 1

        if all_subs == 0 or completed == 0:
            return 0
        return 100 * completed // all_subs
    
    @property
    def progress_class(self):
        if self.progress < 40:
            return 'danger'
        elif self.progress < 70:
            return 'warning'
        return 'success'

    @property
    def status(self):
        if self.progress < 100:
            return 'inprogress'
        return 'completed'

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=128)
    start = models.DateTimeField(auto_now=True)
    end = models.DateTimeField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

    @property
    def progress(self):
        subs = SubTask.objects.filter(task_id=self.id)
        completed = subs.filter(is_completed=True)

        if subs.count() == 0:
            return 0
        return 100 * completed.count() // subs.count()
    
    @property
    def progress_class(self):
        if self.progress < 40:
            return 'danger'
        elif self.progress < 70:
            return 'warning'
        return 'success'

    @property
    def status(self):
        if self.progress < 100:
            return 'inprogress'
        return 'completed'


class SubTask(models.Model):
    description = models.CharField(max_length=128)
    is_completed = models.BooleanField(default=False)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

class Notification(models.Model):
    title = models.CharField(max_length=128)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.title

allocator/forms.py
from django import forms
from .models import User, Task, Project


class DateInput(forms.DateInput):
    input_type = 'date'


class TaskForm(forms.Form):
    user = forms.ModelChoiceField(
        queryset=User.objects.filter(is_employee=True),
        widget=forms.Select(
            attrs={
                "class": "form-control"
            }
        )
    )
    description = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "description",
                "class": "form-control"
            }
        )
    )
    sub_tasks = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "placeholder": "comma seperated sub tasks",
                "class": "form-control"
            }
        )
    )
    end = forms.DateTimeField(
        widget=DateInput(
            attrs={
                "class": "form-control"
            }
        )
    )


class ProjectForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Project Name",
                "class": "form-control"
            }
        )
    )
    description = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "description",
                "class": "form-control"
            }
        )
    )
    end = forms.DateTimeField(
        widget=DateInput(
            attrs={
                "class": "form-control"
            }
        )
    )

allocator/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse


from django.shortcuts import render
from django.views import View
from django.http import HttpResponse

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout

from .models import User, Task, Project, Notification, SubTask
from .forms import TaskForm, ProjectForm

import datetime

# Create your views here.

class IndexView(View):
    title = 'Welcome'

    def get(self, request):

        context = {
            'title': self.title,
        }
        # return HttpResponse("Home Page")
        return render(request, 'landing.html', context)

    def post(self, request):
        context = {
            'title': self.title,
        }
        if 'login' in request.POST:
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('allocator:dashboard')
            else:
                context['message'] = 'Invalid Credentials, try again!'
            return render(request, 'landing.html', context)

        if 'register' in request.POST:
            username = request.POST['email']
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']
            password = request.POST['password']

            # check if user exist
            try:

                user_exist = User.objects.get(username=username)
                if user_exist:
                    context['message'] = 'Username already taken'
                    return render(request, 'landing.html', context)
            except:
                new_user = User(
                    username = username,
                    email = username,
                    first_name = first_name,
                    last_name = last_name,
                )
                if 'manager' in request.POST:
                    new_user.is_manager = True
                    new_user.is_staff = True
                else:
                    new_user.is_employee = True
                new_user.set_password(password)

                new_user.save()

                user = authenticate(request, username=username, password=password)

                if user is not None:
                    login(request, user)
                    return redirect('allocator:dashboard')
            return HttpResponse('unsuccessful')


def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return HttpResponseRedirect(reverse('allocator:landing'))


class DashboardView(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request):
        title = 'Dashboard'
        tasks = Task.objects.all()
        users = User.objects.all().filter(is_active=True) # employees
        notifications = Notification.objects.filter(user_id=request.user.id)

        context = {
            'title': title,
            'segment': ['dashboard'],
        }
        if request.user.is_employee:
            user_tasks = tasks.filter(user=request.user)
            
            completed = 0
            for t in user_tasks:
                if t.status == 'completed':
                    completed += 1

            context['tasks'] = user_tasks[:5]
            context['task_count'] = user_tasks.count()
            context['completed_tasks'] = completed #status='completed'
            context['outstanding_tasks'] = user_tasks.count() - completed #status='inprogress'
            context['notifications'] = notifications

            return render(request, 'employee_dashboard.html', context)
        else:
            outstanding = 0
            for t in tasks:
                if t.status == 'inprogress':
                    outstanding += 1
            employees = users.filter(is_employee=True)
            if request.user.is_manager:
                context['users'] = employees
                context['user_count'] = employees.count()
            else:
                context['users'] = users
                context['user_count'] = users.count()
            context['tasks'] = tasks[:5]
            context['outstanding'] = outstanding
            context['project_count'] = Project.objects.all().count()

            return render(request, 'staff_dashboard.html', context)

    def post(self, request):
        return HttpResponse("Dashboard: post")

class AllNotificationsView(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request):
        if not request.user.is_employee:
            return HttpResponseRedirect(reverse('allocator:dashboard'))
        title = 'Dashboard'
        notifications = Notification.objects.filter(user=request.user)
        context = {
            'title': title,
            'segment': ['dashboard'],
            'notifications': notifications,
            'back': True
        }
        return render(request, 'all_notifications.html', context)


class NotificationView(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request, id):
        if not request.user.is_employee:
            return HttpResponseRedirect(reverse('allocator:dashboard'))
        title = 'Dashboard'
        notification = Notification.objects.get(pk=id)
        context = {
            'title': title,
            'segment': ['dashboard'],
            'notification': notification,
            'notifications': Notification.objects.filter(user=request.user),
            'back': True
        }
        return render(request, 'notification.html', context)

class DeleteNotificationView(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request, id):
        notification = Notification.objects.get(id=id)
        if notification != None:
            notification.delete()
            return HttpResponseRedirect(reverse('allocator:dashboard'))
        else:
            return HttpResponseRedirect(reverse('allocator:notification', args=(id,)))
    
class EmployeeTasksView(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request):
        if not request.user.is_employee:
            return HttpResponseRedirect(reverse('allocator:dashboard'))
        title = 'My Tasks'
        tasks = Task.objects.all().filter(user=request.user)

        context = {
            'title': title,
            'tasks': tasks,
            'segment': ['tasks'],
            'back': True
        }
        return render(request, 'employee_tasks.html', context)

class AllProjectsView(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request):
        if request.user.is_employee:
            return HttpResponseRedirect(reverse('allocator:dashboard'))
        title = 'All Projects'
        projects = Project.objects.all()
        form = ProjectForm(request.POST or None)

        context = {
            'title': title,
            'projects': projects,
            'segment': ['projects'],
            'project_form': form,
            'back': True
        }
        return render(request, 'all_projects.html', context)

    def post(self, request):
        if request.user.is_employee:
            return HttpResponseRedirect(reverse('allocator:dashboard'))
        title = 'All Projects'
        projects = Project.objects.all()
        form = ProjectForm(request.POST or None)
        if form.is_valid():
            
            new_project = Project(
                name=form.cleaned_data.get("name"),
                description=form.cleaned_data.get("description"),
                end = form.cleaned_data.get("end"),
            )
            new_project.save()
            msg = 'project creation successful'

        else:
            msg = 'Error validating the form'

        context = {
            'title': title,
            'projects': projects,
            'segment': ['projects'],
            'project_form': form,
            'back': True
        }
        return render(request, 'all_projects.html', context)


class ProjectView(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request, id):
        title = 'Project'
        project = Project.objects.get(id=id)
        tasks = Task.objects.filter(project_id=id)
        form = TaskForm(request.POST or None)

        context = {
            'title': title,
            'project': project,
            'tasks': tasks,
            'segment': ['projects'],
            'task_form': form,
            'back': True
        }
        return render(request, 'project.html', context)

    def post(self, request, id):
        title = 'All Tasks'
        tasks = Task.objects.all()
        project = Project.objects.get(id=id)
        users = User.objects.all() # employees
        project_count = Project.objects.all().count()
        form = TaskForm(request.POST or None)
        if form.is_valid():
            
            new_task = Task(
                description=form.cleaned_data.get("description"),
                project_id=id,
                user = form.cleaned_data.get("user"),
                end = form.cleaned_data.get("end")
            )
            new_task.save()
            subs = form.cleaned_data.get("sub_tasks").split(",")
            if len(subs) == 0:
                SubTask.objects.create(
                    description=form.cleaned_data.get("description"),
                    task_id = new_task.id
                )
            else:
                for sub in subs:
                    SubTask.objects.create(
                        description=sub.strip(),
                        task_id = new_task.id
                    )
            msg = 'task creation successful'

        else:
            msg = 'Error validating the form'

        context = {
            'title': title,
            'project': project,
            'tasks': tasks,

allocator/templates/all_projects.html
{% extends "includes/base-dash.html" %}

{% block title %} Task {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<!-- Modal Content -->
<div class="modal fade" id="modal-form-project" tabindex="-1" role="dialog" aria-labelledby="modal-form-project" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body p-0">
                <div class="card p-3 p-lg-4">
                    <button type="button" class="btn-close ms-auto" data-bs-dismiss="modal" aria-label="Close"></button>
                    <div class="text-center text-md-center mb-4 mt-md-0">
                        <h1 class="mb-0 h4">New Project</h1>
                    </div>
                    <form method="post" class="mt-4">
                        {% csrf_token %}
                        <!-- Form -->
                        {{ project_form }}
                        <div class="d-grid">
                            <button type="submit" class="btn btn-gray-800">Create Project</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End of Modal Content -->
{% if msg %}
<div class=" justify-content-center flex-wrap flex-md-nowrap align-items-center py-4">
    <div class="d-block mb-4 mb-md-0">
        <h2 class="h4">
            {{ msg }}
        </h2>
    </div>
</div>
{% endif %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    <div class="d-block mb-4 mb-md-0">
        <h2 class="h4">
            ALL PROJECTS
        </h2>
    </div>
    <div class="btn-toolbar mb-2 mb-md-0">
        <!-- Modal Button -->
        <button type="button" class="btn btn-block btn-gray-800 mb-3" data-bs-toggle="modal" data-bs-target="#modal-form-project">New Project</button>
        <!-- End of Modal Button -->
    </div>
</div>

<div class="card border-0 shadow mb-4">
    <div class="card-body">
        {% if projects %}
        <div class="table-responsive">
            <table class="table table-centered table-nowrap mb-0 rounded">
                <thead class="thead-light">
                    <tr>
                        <th class="border-0 rounded-start">#</th>
                        <th class="border-0">Project</th>
                        <th class="border-0">Start</th>
                        <th class="border-0">End</th>
                        <th class="border-0">Status</th>
                        <th class="border-0 rounded-end">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for project in projects %}
                    <!-- Item -->
                    <tr>
                        <td>{{ forloop.counter }}</a> </td>
                        <td>
                            <a href="{% url 'allocator:project' id=project.id %}" class="text-primary fw-bold">{{ project.name }}</a>
                        </td>
                        <td>
                            {{ project.start }}
                        </td>
                        <td>
                            {{ project.end }}
                        <td><span class="fw-bold text-{{ project.progress_class }}">{{ project.status }}</span></td>
                        <td>
                            <a href="{% url 'allocator:project' id=project.id %}" class="btn btn-outline-success">View</a>
                            <a href="{% url 'allocator:edit_project' id=project.id %}" class="btn btn-outline-warning">Edit</a>
                            <a href="{% url 'allocator:delete_project' id=project.id %}" class="btn btn-outline-danger">Delete</a>
                        </td>                        
                    </tr>
                    <!-- End of Item -->
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
            <p class="mt-4 mb-4 text-center">No Projects yet!!!</p>
        {% endif %}
</div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

allocator/templates/all_tasks.html
{% extends "includes/base-dash.html" %}

{% block title %} Task {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<!-- Modal Content -->
<div class="modal fade" id="modal-form-signup" tabindex="-1" role="dialog" aria-labelledby="modal-form-signup" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body p-0">
                <div class="card p-3 p-lg-4">
                    <button type="button" class="btn-close ms-auto" data-bs-dismiss="modal" aria-label="Close"></button>
                    <div class="text-center text-md-center mb-4 mt-md-0">
                        <h1 class="mb-0 h4">New Task</h1>
                    </div>
                    <form method="post" class="mt-4">
                        {% csrf_token %}
                        <!-- Form -->
                        {{ form }}
                        <div class="d-grid">
                            <button type="submit" class="btn btn-gray-800">Add Task</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End of Modal Content -->
{% if msg %}
<div class=" justify-content-center flex-wrap flex-md-nowrap align-items-center py-4">
    <div class="d-block mb-4 mb-md-0">
        <h2 class="h4">
            {{ msg }}
        </h2>
    </div>
</div>
{% endif %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    <div class="d-block mb-4 mb-md-0">
        <h2 class="h4">
            ALL TASKS
        </h2>
    </div>
    <div class="btn-toolbar mb-2 mb-md-0">
        <!-- Modal Button -->
        <button type="button" class="btn btn-block btn-gray-800 mb-3" data-bs-toggle="modal" data-bs-target="#modal-form-signup">New Task</button>
        <!-- End of Modal Button -->
    </div>
</div>

<div class="card border-0 shadow mb-4">
    <div class="card-body">
        {% if tasks %}
        <div class="table-responsive">
            <table class="table table-centered table-nowrap mb-0 rounded">
                <thead class="thead-light">
                    <tr>
                        <th class="border-0 rounded-start">#</th>
                        <th class="border-0">Task</th>
                        <th class="border-0">User</th>
                        <th class="border-0">Project</th>
                        <th class="border-0">Start</th>
                        <th class="border-0">End</th>
                        <th class="border-0">Status</th>
                        <th class="border-0 rounded-end">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                    <!-- Item -->
                    <tr>
                        <td>{{ forloop.counter }}</a> </td>
                        <td>
                            <a href="{% url 'allocator:task' id=task.id %}" class="text-primary fw-bold">{{ task.description }}</a>
                        </td>
                        <td>
                            {{ task.user.username }}
                        </td>
                        <td>
                            {{ task.project.name }}
                        </td>
                        <td>
                            {{ task.start }}
                        <td>
                            {{ task.end }}
                        </td>
                        <td><span class="fw-bold text-{{ task.progress_class }}">{{ task.status }}</span></td>
                        <td>
                            <a href="{% url 'allocator:delete_task' id=task.id %}" class="btn btn-outline-danger">Delete</a>
                        </td>                        
                    </tr>
                    <!-- End of Item -->
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
            <p class="mt-4 mb-4 text-center">No tasks yet!!!</p>
        {% endif %}
</div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

allocator/templates/notification.html
{% extends "includes/base-dash.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="card border-0 shadow mb-4">
    <div class="card-body">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h2 class="fs-5 fw-bold mb-0">{{ notification.title }}</h2>
            <a href="{% url 'allocator:delete_notification' id=notification.id %}" class="btn btn-outline-danger">Delete</a>
        </div>
        <p>{{ notification.description }}</p>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

allocator/templates/project.html
{% extends "includes/base-dash.html" %}

{% block title %} Transactions {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<!-- Modal Content -->
<div class="modal fade" id="modal-form-new-task" tabindex="-1" role="dialog" aria-labelledby="modal-form-signup" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body p-0">
                <div class="card p-3 p-lg-4">
                    <button type="button" class="btn-close ms-auto" data-bs-dismiss="modal" aria-label="Close"></button>
                    <div class="text-center text-md-center mb-4 mt-md-0">
                        <h1 class="mb-0 h4">New Task</h1>
                    </div>
                    <form method="post" class="mt-4">
                        {% csrf_token %}
                        <!-- Form -->
                        {{ task_form }}
                        <div class="d-grid">
                            <button type="submit" class="btn btn-gray-800">Add Task</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End of Modal Content -->

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    <div class="d-block mb-4 mb-md-0">
        <h2 class="h4">
            Project Details
        </h2>
    </div>
    <div class="btn-toolbar mb-2 mb-md-0">
        <!-- Modal Button -->
        <a href="{% url 'allocator:edit_project' id=project.id %}" class="btn btn-block btn-gray-800 mb-3">Edit</a>
        <!-- End of Modal Button -->
    </div>
</div>

<div class="row">
    <div class="col-12">
        
        <div class="card card-body border-0 shadow mb-4">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h2 class="fs-5 fw-bold mb-0">{{ project.name }}</h2>
                <a href="{% url 'allocator:delete_project' id=project.id %}" class="btn btn-outline-danger">Delete Project</a>
            </div>
            <div class="row mb-4 mt-4">
                <div class="col-auto">
                    <svg class="icon icon-sm text-gray-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z"></path><path fill-rule="evenodd" d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3 4a1 1 0 000 2h.01a1 1 0 100-2H7zm3 0a1 1 0 000 2h3a1 1 0 100-2h-3zm-3 4a1 1 0 100 2h.01a1 1 0 100-2H7zm3 0a1 1 0 100 2h3a1 1 0 100-2h-3z" clip-rule="evenodd"></path></svg>
                </div>
                <div class="col">
                    <div class="progress-wrapper">
                        <div class="progress-info">
                            <div class="h6 mb-0">Progress</div>
                            <div class="small fw-bold text-gray-500"><span>{{ project.progress }}% Completed</span></div>
                        </div>
                        <div class="progress mb-0">
                            <div class="progress-bar bg-{{ project.progress_class }}" role="progressbar" aria-valuenow="{{ project.progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ project.progress }}%;"></div>
                        </div>
                    </div>
                </div>
            </div>
            <h2 class="fs-5 fw-bold mb-1">Description</h2>
            <p>{{ project.description }}</p>
            <h2 class="fs-5 fw-bold mb-1">Start Date</h2>
            <p>{{ project.start }}</p>
            <h2 class="fs-5 fw-bold mb-1">End Date</h2>
            <p>{{ project.end }}</p>
        </div>
        <div class="card-header d-flex align-items-center justify-content-between">
            <h2 class="fs-5 fw-bold mb-0">Project Tasks</h2>
            <button type="button" class="btn btn-block btn-gray-800 mb-3" data-bs-toggle="modal" data-bs-target="#modal-form-new-task">New Task</button>
        </div>
        {% if tasks %}
        <div class="table-responsive">
            <table class="table table-centered table-nowrap mb-0 rounded">
                <thead class="thead-light">
                    <tr>
                        <th class="border-0 rounded-start">#</th>
                        <th class="border-0">Description</th>
                        <th class="border-0 rounded-end">Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                    <!-- Item -->
                    
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            {{ task.description }}
                            <span>
                                <a href="{% url 'allocator:task' id=task.id %}" class="btn btn-sm btn-success">See details</a>
                            </span>
                        </td>
                        <td> {{ task.status }} </td>                        
                    </tr>
                    <!-- End of Item -->
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p> No Task for this project yet! </p>
        {% endif %}
</div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}