allocator/urls.py
from django.urls import path
from .views import (
    IndexView,
    logout_view,
    DashboardView,
    TaskView,
    DeleteTaskView,
    CompleteSubTaskView,
    NotificationView,
    AllNotificationsView,
    DeleteNotificationView,
    EmployeeTasksView,
    AllProjectsView,
    ProjectView,
    DeleteProjectView,
    AllUserView,
    EditProjectView,
    DeactivateUserView
)

app_name = 'allocator'

urlpatterns = [
    path('', IndexView.as_view(), name='landing'),
    path('logout/', logout_view, name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('tasks/', EmployeeTasksView.as_view(), name='employee_tasks'),
    path('tasks/<int:id>/', TaskView.as_view(), name='task'),
    path('tasks/<int:id>/delete', DeleteTaskView.as_view(), name='delete_task'),
    path('tasks/<int:taskid>/<int:subid>', CompleteSubTaskView.as_view(), name='complete_task'),
    path('notifications/', AllNotificationsView.as_view(), name='all_notifications'),
    path('notifications/<int:id>/', NotificationView.as_view(), name='notification'),
    path('notifications/<int:id>/delete', DeleteNotificationView.as_view(), name='delete_notification'),
    path('projects/', AllProjectsView.as_view(), name='all_projects'),
    path('projects/<int:id>/', ProjectView.as_view(), name='project'),
    path('projects/<int:id>/delete', DeleteProjectView.as_view(), name='delete_project'),
    path('projects/<int:id>/edit', EditProjectView.as_view(), name='edit_project'),
    path('users/', AllUserView.as_view(), name='users'),
    path('users/<int:id>/deactivate', DeactivateUserView.as_view(), name='deactivate_user'),
]

taskallocator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('allocator.urls'))
]

allocator/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User


# Create your models here.


class User(AbstractUser):
    is_manager = models.BooleanField(default=False)
    is_employee = models.BooleanField(default=False)

    def __str__(self):
        return self.first_name
    
    @property
    def pending_tasks(self):
        tasks = Task.objects.filter(user_id=self.pk)
        return tasks.count()


class Project(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=40)
    start = models.DateField(auto_now_add=True)
    end = models.DateField()

    def __str__(self):
        return self.name

    @property
    def progress(self):
        tasks = Task.objects.filter(project_id=self.pk)
        all_subs = 0
        completed = 0
        for t in tasks:
            subtasks = SubTask.objects.filter(task_id=t.id)
            all_subs += subtasks.count()
            for sub in subtasks:
                if sub.is_completed:
                    completed += 1

        if all_subs == 0 or completed == 0:
            return 0
        return 100 * completed // all_subs
    
    @property
    def progress_class(self):
        if self.progress < 40:
            return 'danger'
        elif self.progress < 70:
            return 'warning'
        return 'success'

    @property
    def status(self):
        if self.progress < 100:
            return 'inprogress'
        return 'completed'

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=128)
    start = models.DateTimeField(auto_now=True)
    end = models.DateTimeField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

    @property
    def progress(self):
        subs = SubTask.objects.filter(task_id=self.id)
        completed = subs.filter(is_completed=True)

        if subs.count() == 0:
            return 0
        return 100 * completed.count() // subs.count()
    
    @property
    def progress_class(self):
        if self.progress < 40:
            return 'danger'
        elif self.progress < 70:
            return 'warning'
        return 'success'

    @property
    def status(self):
        if self.progress < 100:
            return 'inprogress'
        return 'completed'


class SubTask(models.Model):
    description = models.CharField(max_length=128)
    is_completed = models.BooleanField(default=False)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

class Notification(models.Model):
    title = models.CharField(max_length=128)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.title

allocator/forms.py
from django import forms
from .models import User, Task, Project


class DateInput(forms.DateInput):
    input_type = 'date'


class TaskForm(forms.Form):
    user = forms.ModelChoiceField(
        queryset=User.objects.filter(is_employee=True),
        widget=forms.Select(
            attrs={
                "class": "form-control"
            }
        )
    )
    description = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "description",
                "class": "form-control"
            }
        )
    )
    sub_tasks = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "placeholder": "comma seperated sub tasks",
                "class": "form-control"
            }
        )
    )
    end = forms.DateTimeField(
        widget=DateInput(
            attrs={
                "class": "form-control"
            }
        )
    )


class ProjectForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Project Name",
                "class": "form-control"
            }
        )
    )
    description = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "description",
                "class": "form-control"
            }
        )
    )
    end = forms.DateTimeField(
        widget=DateInput(
            attrs={
                "class": "form-control"
            }
        )
    )

allocator/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse


from django.shortcuts import render
from django.views import View
from django.http import HttpResponse

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout

from .models import User, Task, Project, Notification, SubTask
from .forms import TaskForm, ProjectForm

import datetime

# Create your views here.

class IndexView(View):
    title = 'Welcome'

    def get(self, request):

        context = {
            'title': self.title,
        }
        # return HttpResponse("Home Page")
        return render(request, 'landing.html', context)

    def post(self, request):
        context = {
            'title': self.title,
        }
        if 'login' in request.POST:
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('allocator:dashboard')
            else:
                context['message'] = 'Invalid Credentials, try again!'
            return render(request, 'landing.html', context)

        if 'register' in request.POST:
            username = request.POST['email']
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']
            password = request.POST['password']

            # check if user exist
            try:

                user_exist = User.objects.get(username=username)
                if user_exist:
                    context['message'] = 'Username already taken'
                    return render(request, 'landing.html', context)
            except:
                new_user = User(
                    username = username,
                    email = username,
                    first_name = first_name,
                    last_name = last_name,
                )
                if 'manager' in request.POST:
                    new_user.is_manager = True
                    new_user.is_staff = True
                else:
                    new_user.is_employee = True
                new_user.set_password(password)

                new_user.save()

                user = authenticate(request, username=username, password=password)

                if user is not None:
                    login(request, user)
                    return redirect('allocator:dashboard')
            return HttpResponse('unsuccessful')


def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return HttpResponseRedirect(reverse('allocator:landing'))


class DashboardView(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request):
        title = 'Dashboard'
        tasks = Task.objects.all()
        users = User.objects.all().filter(is_active=True) # employees
        notifications = Notification.objects.filter(user_id=request.user.id)

        context = {
            'title': title,
            'segment': ['dashboard'],
        }
        if request.user.is_employee:
            user_tasks = tasks.filter(user=request.user)
            
            completed = 0
            for t in user_tasks:
                if t.status == 'completed':
                    completed += 1

            context['tasks'] = user_tasks[:5]
            context['task_count'] = user_tasks.count()
            context['completed_tasks'] = completed #status='completed'
            context['outstanding_tasks'] = user_tasks.count() - completed #status='inprogress'
            context['notifications'] = notifications

            return render(request, 'employee_dashboard.html', context)
        else:
            outstanding = 0
            for t in tasks:
                if t.status == 'inprogress':
                    outstanding += 1
            employees = users.filter(is_employee=True)
            if request.user.is_manager:
                context['users'] = employees
                context['user_count'] = employees.count()
            else:
                context['users'] = users
                context['user_count'] = users.count()
            context['tasks'] = tasks[:5]
            context['outstanding'] = outstanding
            context['project_count'] = Project.objects.all().count()

            return render(request, 'staff_dashboard.html', context)

    def post(self, request):
        return HttpResponse("Dashboard: post")

class AllNotificationsView(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request):
        if not request.user.is_employee:
            return HttpResponseRedirect(reverse('allocator:dashboard'))
        title = 'Dashboard'
        notifications = Notification.objects.filter(user=request.user)
        context = {
            'title': title,
            'segment': ['dashboard'],
            'notifications': notifications,
            'back': True
        }
        return render(request, 'all_notifications.html', context)


class NotificationView(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request, id):
        if not request.user.is_employee:
            return HttpResponseRedirect(reverse('allocator:dashboard'))
        title = 'Dashboard'
        notification = Notification.objects.get(pk=id)
        context = {
            'title': title,
            'segment': ['dashboard'],
            'notification': notification,
            'notifications': Notification.objects.filter(user=request.user),
            'back': True
        }
        return render(request, 'notification.html', context)

class DeleteNotificationView(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request, id):
        notification = Notification.objects.get(id=id)
        if notification != None:
            notification.delete()
            return HttpResponseRedirect(reverse('allocator:dashboard'))
        else:
            return HttpResponseRedirect(reverse('allocator:notification', args=(id,)))
    
class EmployeeTasksView(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request):
        if not request.user.is_employee:
            return HttpResponseRedirect(reverse('allocator:dashboard'))
        title = 'My Tasks'
        tasks = Task.objects.all().filter(user=request.user)

        context = {
            'title': title,
            'tasks': tasks,
            'segment': ['tasks'],
            'back': True
        }
        return render(request, 'employee_tasks.html', context)

class AllProjectsView(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request):
        if request.user.is_employee:
            return HttpResponseRedirect(reverse('allocator:dashboard'))
        title = 'All Projects'
        projects = Project.objects.all()
        form = ProjectForm(request.POST or None)

        context = {
            'title': title,
            'projects': projects,
            'segment': ['projects'],
            'project_form': form,
            'back': True
        }
        return render(request, 'all_projects.html', context)

    def post(self, request):
        if request.user.is_employee:
            return HttpResponseRedirect(reverse('allocator:dashboard'))
        title = 'All Projects'
        projects = Project.objects.all()
        form = ProjectForm(request.POST or None)
        if form.is_valid():
            
            new_project = Project(
                name=form.cleaned_data.get("name"),
                description=form.cleaned_data.get("description"),
                end = form.cleaned_data.get("end"),
            )
            new_project.save()
            msg = 'project creation successful'

        else:
            msg = 'Error validating the form'

        context = {
            'title': title,
            'projects': projects,
            'segment': ['projects'],
            'project_form': form,
            'back': True
        }
        return render(request, 'all_projects.html', context)


class ProjectView(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request, id):
        title = 'Project'
        project = Project.objects.get(id=id)
        tasks = Task.objects.filter(project_id=id)
        form = TaskForm(request.POST or None)

        context = {
            'title': title,
            'project': project,
            'tasks': tasks,
            'segment': ['projects'],
            'task_form': form,
            'back': True
        }
        return render(request, 'project.html', context)

    def post(self, request, id):
        title = 'All Tasks'
        tasks = Task.objects.all()
        project = Project.objects.get(id=id)
        users = User.objects.all() # employees
        project_count = Project.objects.all().count()
        form = TaskForm(request.POST or None)
        if form.is_valid():
            
            new_task = Task(
                description=form.cleaned_data.get("description"),
                project_id=id,
                user = form.cleaned_data.get("user"),
                end = form.cleaned_data.get("end")
            )
            new_task.save()
            subs = form.cleaned_data.get("sub_tasks").split(",")
            if len(subs) == 0:
                SubTask.objects.create(
                    description=form.cleaned_data.get("description"),
                    task_id = new_task.id
                )
            else:
                for sub in subs:
                    SubTask.objects.create(
                        description=sub.strip(),
                        task_id = new_task.id
                    )
            msg = 'task creation successful'

        else:
            msg = 'Error validating the form'

        context = {
            'title': title,
            'project': project,
            'tasks': tasks,

allocator/templates/includes/base-dash.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head> 
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- Primary Meta Tags -->

<title>{{ title }}</title>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="{% static 'assets/img/logo.png' %}" rel="icon">

<!-- Specific Page JS goes HERE  -->    
{% block stylesheets %}{% endblock stylesheets %}
</head>
<body>

    {% include 'includes/sidebar.html' %}
    
    <main class="content">

      {% include 'includes/navigation.html' %}

      {% block content %}{% endblock content %} 

    </main>

  {% include 'includes/scripts.html' %}
    
  <!-- Specific Page JS goes HERE  -->
  {% block javascripts %}{% endblock javascripts %}  
      
</body>
</html>

allocator/templates/includes/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Task Allocation & Monitor | {{ title }}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/logo.png' %}" rel="icon">
  <!-- <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon"> -->

  <!-- Vendor CSS Files -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- Option 1: Include in HTML -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

<!-- Template Main CSS File -->
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
<script>
  {% if message %}
    var msg = document.getElementById('msg');
    msg.style.display = "block";
  {% endif %}
</script>
  {% block css %}
  {% endblock css %}

</head>

<body>
  <!-- ======= POST Message ======= -->
  <div id="msg" class="container-fluid d-flex align-items-center justify-content-center" style="display: none;">
    <h4 style="color: red;">{{ message }}</h4>
  </div>
    <!-- ======= end of POST Message ======= -->
  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="{% url 'allocator:landing'%}" class="logo d-flex align-items-center">
        <img src="{% static 'assets/img/logo.png' %}" alt="">
        <span>Task Allocation System</span>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'allocator:landing' %}">Home</a></li>
          {% if request.user.is_authenticated %}
          <li><a class="nav-link scrollto active" href="{% url 'allocator:dashboard' %}">Dashboard</a></li>
          <li><a class="getstarted scrollto" href="{% url 'allocator:logout' %}">Logout</a></li>
          {% else %}
          <li><button class="getstarted scrollto" style="border: none;" onclick="document.getElementById('id02').style.display='block'">Signup as Manager</button></li>
          <li><button class="getstarted scrollto" style="border: none;" onclick="document.getElementById('id01').style.display='block'">Login</button></li>
          {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header>
<!-- End Header -->
    {% block content %}
    {% endblock content %}

    {% block scripts %}
    {% endblock scripts %}
  
</body>

</html>

allocator/templates/includes/navigation.html
{% load static %}

<nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark ps-0 pe-2 pb-0">
  <div class="container-fluid px-0">
    <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
      <div class="d-flex align-items-center">
        <!-- Search form -->
        {% if back %}
          <btn id="go-back" onclick="window.history.back()" class="btn btn-sm btn-primary">Go back</btn>
        {% endif %}
        <!-- / Search form -->
      </div>
      <!-- Navbar links -->
                  <ul class="navbar-nav align-items-center">
                    <li class="nav-item dropdown">
                      <a class="nav-link text-dark notification-bell unread dropdown-toggle" data-unread-notifications="true" href="#" role="button" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                        <svg class="icon icon-sm text-gray-900" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z"></path></svg>
                      </a>
                      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-center mt-2 py-0">
                        <div class="list-group list-group-flush">
                          <a href="#" class="text-center text-primary fw-bold border-bottom border-light py-3">Notifications</a>
                          {% if notifications %}
                          {% for notification in notifications %}
                          <a href="{% url 'allocator:notification' id=notification.id %}" class="list-group-item list-group-item-action border-bottom">
                            <div class="row align-items-center">
                                <div class="col-auto">
                                  <!-- Avatar -->
                                  <img alt="Image placeholder" src="{% static 'assets/img/team/profile-picture-0.jpg' %}" class="avatar-md rounded">
                                </div>
                                <div class="col ps-0 ms-2">
                                  <div class="d-flex justify-content-between align-items-center">
                                      <div>
                                        <h4 class="h6 mb-0 text-small">{{ notification.title }}</h4>
                                      </div>
                                      <div class="text-end">
                                        <small class="text-danger">{{ notification.date }}</small>
                                      </div>
                                  </div>
                                  <p class="font-small mt-1 mb-0">{{ notification.description }}</p>
                                </div>
                            </div>
                          </a>
                          {% endfor %}
                          <a href="{% url 'allocator:all_notifications' %}" class="dropdown-item text-center fw-bold rounded-bottom py-3">
                            <svg class="icon icon-xxs text-gray-400 me-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 12a2 2 0 100-4 2 2 0 000 4z"></path><path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd"></path></svg>
                            View all
                          </a>
                          {% else %}
                          <p class="font-small mt-1 mb-0">You don't have any notification for now</p>
                          {% endif %}
                        </div>
                      </div>
                    </li>
                    <li class="nav-item dropdown ms-lg-3">
                      <a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <div class="media d-flex align-items-center">
                          <img class="avatar rounded-circle" alt="Image placeholder" src="{% static 'assets/img/team/profile-picture-0.jpg' %}">
                          <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block">
                            <span class="mb-0 font-small fw-bold text-gray-900">
                              Current User: <strong>{{ request.user.username }}</strong>
                            </span>
                          </div>
                        </div>
                      </a>
                      <div class="dropdown-menu dashboard-dropdown dropdown-menu-end mt-2 py-1">
                        <div role="separator" class="dropdown-divider my-1"></div>
                        <a class="dropdown-item d-flex align-items-center" href="{% url 'allocator:logout' %}">
                          <svg class="dropdown-icon text-danger me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>                
                          Logout
                        </a>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>

allocator/templates/includes/sidebar.html
{% load static %}

<nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-lg-none">
    <a class="navbar-brand me-lg-5" href="/">
        <img class="navbar-brand-dark" src="{% static 'assets/img/logo.png' %}" alt="Volt logo" /> <img class="navbar-brand-light" src="/static/assets/img/brand/dark.svg" alt="Volt logo" />
    </a>
    <div class="d-flex align-items-center">
        <button class="navbar-toggler d-lg-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>

<nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
  <div class="sidebar-inner px-4 pt-3">
    <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
      <div class="d-flex align-items-center">
        <div class="d-block">
          <h2 class="h5 mb-3">Hi, {{ request.user.username}}</h2>
          <a href="{% url 'allocator:logout' %}" class="btn btn-secondary btn-sm d-inline-flex align-items-center">
            <svg class="icon icon-xxs me-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>            
            Sign Out
          </a>
        </div>
      </div>
      <div class="collapse-close d-md-none">
        <a href="#sidebarMenu" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true"
            aria-label="Toggle navigation">
            <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          </a>
      </div>
    </div>
    <ul class="nav flex-column pt-3 pt-md-0">
      <li class="nav-item">
        <a href="/" class="nav-link d-flex align-items-center">
          <span class="sidebar-icon">
            <img src="{% static 'assets/img/logo.png' %}" height="20" width="20" alt="Logo">
          </span>
          <span class="mt-1 ms-1 sidebar-text">eTasks </span>
        </a>
      </li>
      <li class="nav-item {% if 'dashboard' in segment %} active {% endif %}">
        <a href="{% url 'allocator:dashboard' %}" class="nav-link">
          <span class="sidebar-icon">
            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
          </span> 
          <span class="sidebar-text">Dashboard</span>
        </a>
      </li>

      <!-- EMPLOYEE LINKS -->
      {% if request.user.is_employee %}
        <li class="nav-item {% if 'tasks' in segment %} active {% endif %}">
          <a href="{% url 'allocator:employee_tasks' %}" class="nav-link">
            <span class="sidebar-icon">
              <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
            </span> 
            <span class="sidebar-text">My Tasks</span>
          </a>
        </li>
      {% endif %}
      <!-- END OF EMPLOYEE LINKS -->

      <!-- MANAGER / ADMIN LINKS -->
      {% if request.user.is_staff %}
        <li class="nav-item {% if 'projects' in segment %} active {% endif %}">
          <a href="{% url 'allocator:all_projects' %}" class="nav-link">
            <span class="sidebar-icon">
              <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
            </span> 
            <span class="sidebar-text">Projects</span>
          </a>
        </li>

        <!-- MANAGER ONLY -->
        {% if request.user.is_manager %}
          <li class="nav-item {% if 'employees' in segment %} active {% endif %}">
            <a href="{% url 'allocator:users' %}" class="nav-link">
              <span class="sidebar-icon">
                <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
              </span> 
              <span class="sidebar-text">Employees</span>
            </a>
          </li>
        {% else %}
        <!-- ADMIN ONLY -->
          <li class="nav-item {% if 'users' in segment %} active {% endif %}">
            <a href="{% url 'allocator:users' %}" class="nav-link">
              <span class="sidebar-icon">
                <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
              </span> 
              <span class="sidebar-text">Users</span>
            </a>
          </li>
        {% endif %} <!-- manager or admin -->
      {% endif %} <!-- is staff -->
      <!-- END OF MANAGER / ADMIN LINKS -->

      <li class="nav-item">
        <a href="{% url 'allocator:logout' %}" class="nav-link">
          <span class="sidebar-icon">
            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
          </span> 
          <span class="sidebar-text">Logout</span>
        </a>
      </li>
    </ul>
  </div>
</nav>